AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Lint/MissingSuper:
  Exclude:
    - lib/bulma_phlex/rails/components/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb

Naming/FileName:
  Exclude:
    - lib/bulma-phlex-rails.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
