AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/bulma-phlex-rails.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
